### ISSUE TITLE
data export

### ISSUE THREAD

**Issue by authule** [credo-science/credo-webapp#22]
Hello, is it possible to:
1) remove the limit (now 10K) on the number of events during the data export?
2) provide sorting of the resulting file not by timestamp field, but by the time_received field (or to choose between various options)
3) could you please give a hint how on time is calculated?

**Comment by koziomek** [comment]
1. We'll look into it. Also, we are exploring different ways of providing data export. What do you think about daily/weekly dumps of events?

2. Done. Events are now queried and sorted by time_received.

3. We are only storing it. You should ask people from https://github.com/credo-science/credo-detector-android

**Comment by koziomek** [comment]
We updated the way we process data export requests. This allowed us to taise the limit of exported events to 500k. Please take a look at the updated documentation:

https://github.com/credo-science/credo-webapp/tree/develop/credoapiv2#apiv2data_export

**Comment by mmagrys** [comment]
Changes merged into release 1.1, expect production access on June 4th.
