### ISSUE TITLE
priority list discussion

### ISSUE THREAD

**Issue by piotrhomola** [credo-science/credo-webapp#24]
can we have a priority list of the issues being resolved or to be resolved? Some things are certainly  more important than the others - we then should discuss what & when. E.g. currently I'd propose to assign the highest priority to the issue #23 (static filter), this is both science and societal - we can't score the championships without this or similar solution enabling disregarding the background signal. Thanks!

**Comment by piotrhomola** [comment]
proposed priority list (maybe I'd change it if time consuming / difficulty is evaluated for each issue):
1. #23
2. #25
3. #26
4. #22
5. #19
6. #21
What do you think?

**Comment by mpawlik** [comment]
So we're left with:
1. #23 
2. #25 
I think we can work on them simultaneously. I'm closing this issue, as the issue seems to be solved.

**Comment by piotrhomola** [comment]
Ok for now, but the idea of a priority list and corresponding discussion
was addressing a long term perspective: any time we will have many issues
open in parallel it would be good to be able to prioritize somehow, but
since we have many points of view: development engineering, science, pr,
legal,... we might often need a discussion. The recent weeks made this need
clear to me - the most important issues from my point of view are handled
as the last ones, without discussion or explanation. Doing this way also in
future would reduce performance and scientific efficiency of the
Collaboration. I'd be completely fine with delaying my issues if I'm only
told at least a bit of explanation, and given a chance to discuss. It works
like that with single issues: if you are not sure the request is needed you
ask for clarification, this is how it should also work with priorities, if
you do not agree with this let us discuss :)

W dniu wtorek, 19 czerwca 2018 Maciej Pawlik <notifications@github.com>
napisał(a):

**Comment by mpawlik** [comment]
Just to clear things up, some tasks were in progress at the time when list was created.

**Comment by piotrhomola** [comment]
Ok

W dniu środa, 20 czerwca 2018 Maciej Pawlik <notifications@github.com>
napisał(a):
