### ISSUE TITLE
total on-time dispalyed

### ISSUE THREAD

**Issue by piotrhomola** [credo-science/credo-webapp#25]
Can we have total on-time displayed as the basic info about the user performance, the same importance as number of hits? On-time is critically important for science, and we still miss a way for an easy way to test whether this basic quantity is received and stored properly. A simple display in the "user view" under the number of detection would be sufficient for the beginning, later it would be great to sort users by their on-time and event rate (number of hits / on-time). Thanks!

**Comment by mpawlik** [comment]
@koziomek can confirm, that we're currently receiving non-zero on-times. We also provide this value during data export.

Regarding calculation of total on-time for each user, we already discussed this matter on one of the meetings (most probably 25.04.2018). We also discussed how such value should be calculated, and from what I remember it was quite complicated and unclear (logic for handling crashes etc). Implementation of such feature would require us to abandon the "stateless" service approach which was adopted to enable easy scaling in the future.

All of the mentioned functionality can be easily implemented as a script parsing data retrieved from our service.

**Comment by piotrhomola** [comment]
Ok, if this is that complicated let us suspend this issue for the time
being, my group is currently trying to understand how to retrieve on-time
for basic cross-checks and test, let us wait until these tests are done,
then it should be more clear to me how to make the issue more precise, most
likely we would need a meeting on this. Displaying ontime on website is not
less important than displaying timestamps and images, we only need to think
how to do this in an optimum way, certainly we do not want to sacrifice
easy scalbility.

W dniu wtorek, 19 czerwca 2018 Maciej Pawlik <notifications@github.com>
napisał(a):

**Comment by koziomek** [comment]
Since https://github.com/credo-science/credo-webapp/commit/c2daa9d2ee752afd1b21978641c574bf9ea93605 we are now displaying on time for some users. I'll monitor the perfomance impact and change things if necessary.

**Comment by piotrhomola** [comment]
Great! After testing the app in a few basic situations it looks ok, thanks!

W dniu środa, 20 czerwca 2018 Krzysztof Oziomek <notifications@github.com>
napisał(a):
