### ISSUE TITLE
detection time displayed in ms

### ISSUE THREAD

**Issue by piotrhomola** [credo-science/credo-webapp#26]
We need detection time to be displayed with larger precision, do distinct between different frames, e.g. to ms level. This is for science and motivation to look into the data of other users via our webapp: several hits with the same time displayed in seconds are less interesting if caught within one frame, i.e. with the same timestamp ("normal" air shower) than if the events occur within the same second but in different frames - this could be a CRE. Thanks!

**Comment by mpawlik** [comment]
Hi, is this feature really needed? I think that during the export, we provide a 'raw' timestamp which allows for millisecond precision.

**Comment by piotrhomola** [comment]
Yes, it is needed. It is to encourage the users to look into the data even
before they start using features like export (some might never want to!). A
very interested physics can be seen by a literally naked eye, just by
looking at timing, in particular if the events with the same detection
second are spread into more than one frames it is already a potential
"wow", so please let us enable the users the chance for seeing "wow",
unless it costs a lot.
Thanks & Best
P.

2018-06-11 11:27 GMT+02:00 Maciej Pawlik <notifications@github.com>:

**Comment by koziomek** [comment]
Resolved in https://github.com/credo-science/credo-webapp/commit/a4ff2f2efdbe4b89b066396c90809c25ce5c3fab

**Comment by mpawlik** [comment]
@koziomek could you please confirm, that timestamps are shown in tool tip while hovering over the human readable date?

**Comment by piotrhomola** [comment]
Thanks, I see the timestamps but this is not I asked for, I asked fo a
human readable format with the ms precision. Yes, I know one can get this
from timestamp but we want to be user friendly, if it does not cost too
much. So to close the issue I propose to show "in tool tip while hoovering
over" the same human readable format but adding miliseconds after a dot:

2018-06-11 12:26:16 -> 2018-06-11 12:26:16.345

Still I do not understand why not to show the milisecond format already in
the default view, without the need of hoovering over - please consider,
this would make the user life easier. If there are serious reasons not to
do so let us please discuss them.

Many thanks and best regards
PH



2018-06-11 12:21 GMT+02:00 Maciej Pawlik <notifications@github.com>:

**Comment by koziomek** [comment]
Changed in https://github.com/credo-science/credo-webapp/commit/8a4afadbd712eaac599e184dd1b5739b1770e709

**Comment by piotrhomola** [comment]
great, thanks!

2018-06-11 13:03 GMT+02:00 Krzysztof Oziomek <notifications@github.com>:
