### ISSUE TITLE
zamiana logo na stronie aplikacji

### ISSUE THREAD

**Issue by slawekstu** [credo-science/credo-webapp#29]
![logotypg](https://user-images.githubusercontent.com/31563126/41318881-2f0464ac-6e9a-11e8-862c-fc35b24674f9.png)

Proszę o zmianę loga na stronie api.credo.science
Zgoda na zamianę otrzymana od Pana dr.Piotra Homoli

**Comment by mpawlik** [comment]
@piotrhomola could you please acknowledge this change?:) @slawekstu seems to be a fresh account.

**Comment by piotrhomola** [comment]
I confirm, the change is proposed by one of our native speakers who said
that "the quest for unexpected" sounds strange, proposed to add "the",
Slawek was very kind to volunteer the imlementation. Thanks!
P.

2018-06-13 10:53 GMT+02:00 Maciej Pawlik <notifications@github.com>:

**Comment by slawekstu** [comment]
![logo-api](https://user-images.githubusercontent.com/31563126/41506218-185289f4-721a-11e8-9997-ffddf11a6dfc.png)

Can I ask you to change the logo again?
The current version of the logo is too heavy (~ 3 MB) and slows down the page load
The new version has only (~ 40 KB)

**Comment by slawekstu** [comment]
Please change the logo at api.credo.science.
We have new logo
![logocredoapi](https://user-images.githubusercontent.com/31563126/45297856-f767b400-b506-11e8-89e0-19fc7b8fee16.png)


Thank you in advance

**Comment by koziomek** [comment]
![credo-logo-site](https://user-images.githubusercontent.com/38071242/45298160-f3886180-b507-11e8-9c4a-4738cb75f579.png)

I'd rather not with the current colour palette of this logo and the site.

**Comment by slawekstu** [comment]
You're right,
I attach a logo with a white color

![logotypcredo](https://user-images.githubusercontent.com/31563126/45298704-9f7e7c80-b509-11e8-9c84-5e13d905af25.png)

**Comment by koziomek** [comment]
Thanks. Updated in https://github.com/credo-science/credo-webapp/commit/634e8350e76fcd281c1c4680778b01120e20d343

**Comment by slawekstu** [comment]
I think this logo will be better.
![credologoapi2](https://user-images.githubusercontent.com/31563126/45352286-723cd780-b5b8-11e8-9583-1a9312f722db.png)
