### ISSUE TITLE
Registration e-mail displayed improperly?

### ISSUE THREAD

**Issue by piotrhomola** [credo-science/credo-webapp#33]
Complaint via Google Paly: "Niestety przy probie rejestracji i podaniu prawidlowego adresu e-mail aplikacja nie chce go przyjac i zwraca jakis kod HTML. Niestety z tego powodu nie koge Wam pomoc udostepniajac swoj telefon. Samsung galaxy s7 edge z adroidem 9."

**Comment by koziomek** [comment]
I checked now and the registration flow works properly. We can't do much without more details.
