### ISSUE TITLE
updating the static web-based filter

### ISSUE THREAD

**Issue by piotrhomola** [credo-science/credo-webapp#35]
The next step on the way to increase the clarity of the web-app, after enabling on-time visibility and providing limited-access "contest view", is to update the static web-based filter, according to the current status of our understanding the current images. I propose the following filter:
1) total on-time > 0, and
2) image taken after on-time incremented for the first time, and
3) avbrightness_max =< 0.01, and
4) maxbrightness_min >= 120, and

We show only statistics of users/teams that meet condition 1) and for those users/teams we display only images that meet 1), 2), and 3). Other images should be saved but not displayed and not counted for statistics. So in practice I think we do filtering for all images just once, assign a "display flag" Yes or No to each of them according to the filtering scheme, and later, continuously, to each newly received image, upon arrival. 

The selection rules should be clear and well visible to the users, so I suggest adding a corresponding static sub-page named "help" or "FAQ" or similar, where we could have some universal text explaining the filters, and later maybe other essential info. What do you think?

**Comment by koziomek** [comment]
After filtering all detectiond through 3 and 4 we are now down to a little over 22k visible detections. Implementing 1 and 2 would require us to keep some state which we already agreed not to do.

**Comment by piotrhomola** [comment]
I do not quite see why 1 and 2 is not possible if 3 and 4 is possible.
Please consider e.g. the following _proposal_: to determine 1 and 2, for
each existing user you do _once_ what you already do: check his ontime,
then if it is > 0, you do one more check whether the user has any hits
after first positive delta time had been received (after his historical
start with positive ontime). If yes, then this particular user has event
statistics > 0, and for all is events received after his historical start
you can reduce 1 and 2 to another condition: if event statistics > 0 then
you assign display Y to the image. Then you only need to treat the "first
event" case: when event statistics is = 0 and an image is received, you
request pings backwards, until you get positive delta time. If you do not
get any positive delta time you have to assign display N, it might be a
detection made with an older version of the app. Everything would be easier
if we could afford a new column with "historical start", but I understand
that we want to avoid new columns. What do you think?

No problem with a significant reduction of events after applying 3 and 4

W dniu środa, 27 czerwca 2018 Krzysztof Oziomek <notifications@github.com>
napisał(a):

**Comment by piotrhomola** [comment]
Important thing: please do not apply any filters before they are not explicitly mentioned in the help/FAQ section, we do not want any cryptic re-ranking, everything transparent, users should have the impression that we know what we are doing :)

**Comment by koziomek** [comment]
Implementing 1 and 2 would require us to fetch additional information from the databse increasing the number of queries at least a few times. It would also make distributing the job of refiltering detections uch more diffucult and storage database heavy. The filters 3 and 4 only have to look at single detection to determine the result.

**Comment by koziomek** [comment]
There is no help/FAQ section on https://api.credo.science site, it is available at https://credo.science and that site is not in this repository.

**Comment by piotrhomola** [comment]
Sorry but I do not get your remark to implementing 1 and 2, could you please refer somehow to my proposal? Could you explain "Fetch additional information"? My proposal was about doing this only once, then we need only to modify one query by adding one more condition: number of events recorded so far. If we cannot restrict the view only to events taken during the detection with ontime then there is no sense in showing ontime, and if we can't show ontime there is no sense in showing anything... Please try to keep in mind the broader view of the mission, not only the technical point, and please do not hesitate to ask if in doubts, here, by e-mail, skype, phone, anyway - we need to understand each other. Thanks!

**Comment by piotrhomola** [comment]
Re FAQ: again it is about the choice between being user friendly and unfriendly. If we show something and not all the events are shown we need to explain at the place where we show, if we are friendly. So please consider addig the help section on api.credo.science where we would place only the text referring directly to the view we propose. Filtering information is essential to understand the view and it should be delvered clearly. If you refuse adding help then please remove all the filters. Thanks

**Comment by piotrhomola** [comment]
It seems I have to further clarify and strenghten my point by withdrawing my issue: if we cannot have easily 1 and 2 and 3 and 4, with a way to adjust 3 and 4 from time to time after a justified request, then please bring back the previous filter view asap, and I propose that we meet in person and discuss before taking further steps. Doing the new filter only partly, e.g. only 3 and 4 as you did - without consulting and with no explanation provided to the users on site, is in my opinion harmful to the project PR. Thank you in advance for your cooperation and understanding.

**Comment by koziomek** [comment]
I agree, we need a meeting in person to discuss some things.
I don't see why changng the filter parameters now is different than before (example: when we first started filtering the data or when we were asked to hide all detections that are not from APIv2).
I would also appreciate if you wrote what exactly should be in the FAQ.

**Comment by piotrhomola** [comment]
Ok, please bring back the old view and let's meet to discuss further
things, let us set the date via e-mail.

W dniu czwartek, 28 czerwca 2018 Krzysztof Oziomek <notifications@github.com>
napisał(a):

**Comment by koziomek** [comment]
We are waiting for the FAQ text.

**Comment by koziomek** [comment]
We are now relabeling all detections and hiding the ones received before user started sending valid on_time data.

What about 3 and 4? Do you have an idea about what those parameters should be?

**Comment by piotrhomola** [comment]
Please disregard 3 and 4, apply only the old filters plus 1 and 2, plus
explanation. The contest view told us that for 3 and 4 we need a deeper
study plus an algorithm to remove images with hot pixels, so I withdraw my
earlier request. So for the time being: old filters unchanged + ontime (1
and 2) + explanation what we are doing in FAQ. Thanks!

W dniu czwartek, 5 lipca 2018 Krzysztof Oziomek <notifications@github.com>
napisał(a):

**Comment by piotrhomola** [comment]
You should contact Piotr Homola (Piotr.Homola@ifj.edu.pl) and describe...

Please replace with:

You should contact CREDO Science Coordinator (credodetector@credo.science) and
describe...

W dniu czwartek, 5 lipca 2018 Krzysztof Oziomek <notifications@github.com>
napisał(a):

**Comment by piotrhomola** [comment]
Is the filtering finished? Detections "before the ontime era" still
visible, see Leszczur or nkg9 in the user listing.

W dniu czwartek, 5 lipca 2018 Krzysztof Oziomek <notifications@github.com>
napisał(a):
