### ISSUE TITLE
Limited contest view 

### ISSUE THREAD

**Issue by piotrhomola** [credo-science/credo-webapp#36]
I propose enabling contest view for a limited number of registeted users at a time. We could do this with a form where a user gives the view parameters (like those invented for the championships) and his/her user name and password. If we expect that requesting contest views will consume too much processing we might limit the number of requests processed simultaneously or grant the contest view only to the limited number of expert users, e.g. by allowing user names only from the expert list. Will it be possible?

**Comment by piotrhomola** [comment]
Can we increase the limit for the number of results shown? Basically in a contest we need to show all the hits to be transparent, although it can of course be shown in pages, like in the user view, with some maximum shown per page. Maybe it makes the thing more complicated but 100 is really too few :(

**Comment by piotrhomola** [comment]
The view works well, thanks! But there will be more things anavoidably to be done to make the view useful, e.g we need a way to disregard (black list) users of whom we know they produce artifacts which cannot be filtered out by simple cuts, see e.g. Christophe Greisberger in the test view https://api.credo.science/web/contest/f5f7d0f2/

**Comment by koziomek** [comment]
Users can now add descriptions and blacklist usernames while calculating contest results.

I've also increased the maximum number of displayed detections to 500. Anything more would require adding pagination which would be hard (because of the way we store contest data).

**Comment by piotrhomola** [comment]
Another thing to consider: once the brightest pixel position is stored, it
could be displayed within the contest view and we then could we enable
manual removing of single images (those with repeating brightest pixels)
plus refresh the view. Alternatively: introduce a filter that would ignore
all images with the same position of a brightest pixels (if the same
position repeated e.g. more than 2 times, 2 as another parameter in the
form)? See e.g. user Alfred in my test view
https://api.credo.science/web/contest/a421a6f5/, suspected of bad pixels,
although not so many :)

2018-07-05 12:27 GMT+02:00 Piotr Homola <piotr.homola@gmail.com>:

**Comment by koziomek** [comment]
I've increased the limit to 1000.

Adding anything more to the contest view would require major backend changes, be very hard and take a lot of time.
The best way to have more advanced contest experience is to create a separate app that would use exported data.
