### ISSUE TITLE
API for Desktop Detectors

### ISSUE THREAD

**Issue by mtsulek** [credo-science/credo-webapp#37]
@piotrhomola @koziomek 

I would like to ask if it is possible to create another request template, an endpoint for credoapiv2 and extend the database with new fields for the Desktop Detector? Each desktop detector will provide ~~100 events per minute and they will not include pictures so it would be better to keep this data in NoSQL but it is not necessary.

My proposition of request template for Desktop Detectors: 
```
{
    "detections": [
        {
            "timestamp": 1519857467609567,
            "latitude": 52.00000000,
            "longitude": 21.00000000,
            "altitude": 168.0,
            "provider": "gps",
            "accuracy": 14.0,
            "pulse_height": 3.1234567890,
            "environment_info": {
                "temperature": 36.1,
                "humidity": 30,
                "pressure": 1030
            }
        },
        {
            "timestamp": 1519857467609,
            "latitude": 52.00000000,
            "longitude": 21.00000000,
            "altitude": 168.0,
            "provider": "manual",
            "accuracy": 14.0,
            "pulse_height": 3.1234567890,
            "environment_info": {
                "temperature": 36.1,
                "humidity": 30,
                "pressure": 1030
            }
        }
    ],
    "device_id": "3h4i3nf3hr08eushfjshekjhdskfjhslkdhfdslhfkdsf",
    "device_type": "desktop_linux",
    "device_model": "Cosmic Watch",
    "device_version": "072018",
    "app_version": "d0.0.1"
 }
```

New data format will require new structure in the database (for example environment_info: temperature,  humidity, pressure; device_version; pulse_height).

| Field | Description | Constraint |
| --- | --- | --- |
| device_id | Device ID | 50 characters or fewer |
|device_type | Device type | 50 characters or fewer|
|device_model   |  Device model  |   50 characters or fewer|
|device_version  (NEW) |  System version   |  50 characters or fewer|
|app_version   |  Application version   |  50 characters or fewer|
|timestamp   |  UNIX timestamp of detection time (in nanoseconds)   |  Integer|
|latitude   |  GPS latitude   |  Floating point number|
|longitude   |  GPS longitude   |  Floating point number|
|altitude  |   Altitude   |  Floating point number|
|provider  |   Location provider  |   20 characters or fewer|
|accuracy   |  Location accuracy   |  Floating point number|
|pulse_height (NEW)|  -  | Floating point number|
|temperature (NEW)| Temperature in Celcius scale  |  Floating point number|
|humidity (NEW) |  Humidity in [%] |  Integer|
|pressure  (NEW)|  Pressure in [hPa] | Integer|

**Comment by piotrhomola** [comment]
I propose that we proceed with connecting of the detectors of new types in steps, the first step should always be trying to stick to the existing protocol, have the thing running continuously and visible in the webapp, and only then introduce other changes, like more fields, alternative database structure, etc. - only if absolutely necessary technically, justified scientifically, or for the imortant PR reasons. So please define the absolute minimum needs to complete the first step.

**Comment by koziomek** [comment]
The `width` and `height` fields are now optional.
Please send the data using the /api/v2/detection endpoint.

Few suggestions:
- raname field `device_version` to `system_version`
- send information about environment directly in detection object
- send data in batches

Your requests would look like:
```
{
    "detections": [
        {
            "timestamp": 1519857467609567,
            "latitude": 52.00000000,
            "longitude": 21.00000000,
            "altitude": 168.0,
            "provider": "gps",
            "accuracy": 14.0,
            "pulse_height": 3.1234567890,
            "temperature": 36.1,
            "humidity": 30,
            "pressure": 1030

        },
        {
            "timestamp": 1519857467609,
            "latitude": 52.00000000,
            "longitude": 21.00000000,
            "altitude": 168.0,
            "provider": "manual",
            "accuracy": 14.0,
            "pulse_height": 3.1234567890,
            "temperature": 36.1,
            "humidity": 30,
            "pressure": 1030

        }
    ],
    "device_id": "3h4i3nf3hr08eushfjshekjhdskfjhslkdhfdslhfkdsf",
    "device_type": "desktop_linux",
    "device_model": "Cosmic Watch",
    "system_version": "072018",
    "app_version": "d0.0.1"
 }
```

For now we decided not to save additional fields. However, you can still keep sending it.

**Comment by koziomek** [comment]
I seems like the value of on_time is not being reset every time a ping is being sent. The idea is that if someone wants to get device total on time from given time period they have to sum the 'on_time' field values from pings sent from the deivce.

Also, you do not have to send a ping as often as every ~10 seconds. The Android app sends them every 10 minutes.

You should also work on sending detections in batches every few minutes. You are wasting resources sending every detection separately.
