### ISSUE TITLE
the brightest pixel postion stored by server and displayed next to each image

### ISSUE THREAD

**Issue by piotrhomola** [credo-science/credo-webapp#38]
As in the title - the first step to better understand super-frequent events composed of bad pixels.

**Comment by koziomek** [comment]
We are now storing the x and y values received from the Android app.

**Comment by piotrhomola** [comment]
Great! When can it be displayed?

W dniu wtorek, 10 lipca 2018 Krzysztof Oziomek <notifications@github.com>
napisał(a):

**Comment by koziomek** [comment]
After caches expire.
