### ISSUE TITLE
Store rest values from ping and detection message in text field

### ISSUE THREAD

**Issue by dzwiedziu-nkg** [credo-science/credo-webapp#39]
For debugging I want to send some JSON values in `ping` and `detection` message. Can you add one text field to table which will store whole text of JSON message?

**Comment by koziomek** [comment]
Are you ok with adding a "metadata" field that would contain JSON object serialized to string (it would be treated by the webapp as opaque string)? It would enable people to add custom attributes to submitted events.

What average and maximum length of that field do you expect?

**Comment by koziomek** [comment]
Ping: @dzwiedziu-nkg

**Comment by koziomek** [comment]
We are going ahead with the proposed changes.

**Comment by koziomek** [comment]
Changes merged and documentation updated.
