### ISSUE TITLE
black list of images with bad pixels?

### ISSUE THREAD

**Issue by piotrhomola** [credo-science/credo-webapp#40]
Any ideas on how to balck list (preven from being displayed) users/iages uploadig images (better) with apparently bad pixels? See e.g. user depe for an example: pixels 89,447 and 1049,1060 repeat too often.

**Comment by koziomek** [comment]
It is complicated but possible. For each user we would have to either look at all of their past detections every time they submit a new one or store somewhere the coordinates and count of their occurence.

Also, after how many repeats of coordinates we assume that there is a hot pixel? 1?

**Comment by koziomek** [comment]
The filter is now implemented.

**Comment by piotrhomola** [comment]
Great! Which selection rule you have finally applied?

**Comment by koziomek** [comment]
We start hiding detections after 1st repetition of coordinates.

**Comment by piotrhomola** [comment]
Thanks. Would it be possible to reject only after 3rd repetition?

**Comment by koziomek** [comment]
It would be more complicated for us and take a while to implement. Also, what are the chances that one user has 2 legitimate detections with the same coordinates?
