### ISSUE TITLE
only active users displayed 

### ISSUE THREAD

**Issue by piotrhomola** [credo-science/credo-webapp#41]
We have on average 50 active users and 3600 registered, 1500 displayed with the current filter. I propose displaying only the users active in the last 24h, only with the updated app. It will make the ranking more dynamic, encourage the users to update and hopefully also to detect more often.

**Comment by koziomek** [comment]
At most we can display number of active users in the last 24h. Anything more would require extensive processing. Shall I proceed?

**Comment by koziomek** [comment]
There are a few issues with this proposal:
- It is out of scope of this application, this application is supposed to provide storage and basic stats functionality. For more complex stats and contests there should be a separate application.
- We do not want to run heavy computation on this database, ideally all of the computation should run offline on data exports.
- We already run some processing on the main database that is heavier that we would like. If we want to support large amount of users we should not have any heavy processing.

**Comment by piotrhomola** [comment]
I do not think you have answered my question. "basic stats functionality" - I ask for nothing else but basic stats, we probably do not agree about definition of "basic", we started a discussion during the meeting but apparently we need to talk more. I agree that more complex things should be handled by a separate app, once I make an issue and it is rejected i find it insufficient to hear about too demanding processing. I'd prefer to be sure that there is no way to overcome the difficulty, any compromise or alternative solution. That is why I proposed more labels, to get better information, and better information is crucial to take decisions essential for the whole project. So in this case I want to be sure that there is no technical hope for any solution within the "basic" assumptions that help users to get more active by showing more dynamic ranking. That is also why I asked about your ideas to help going in this direction, you know by far better than me what is technically affordable, but let me repeat that apart from technical perfectness we also need to be user friendly and functional, there is and there always will be a fight between these two points of view - and we need to learn how to reach compromise. We have the "minimum display concept" or "trailer view" and I'm asking whether you have any ideas that would bring us closer to "last 24h stats" or not. If you classify the request as N+D+Q then I'll not be pushing anymore, but it would be great if you could keep your technical creativity active to support the merit of the project, in order to look for compromise solution that would not require increasing computing time, for instance what if we re-consider the processing performed now, maybe give up some operations that were useful until now but might be less needed with the dynamic ranking. I insist not for the pleasure of discussion, I just think the current display is below the minimum, not yet the trailer view. And please also keep in mind that the requirements for the trailer view will be changing anyway, for instance because of some new detector types joining the system, so we must be prepared to adjust the system accordingly, to add new features but also to remove or modify the old ones if necessary to keep the processing reasonable.

**Comment by koziomek** [comment]
Not feasible with current architecture and resources.
