### ISSUE TITLE
Problem with data access

### ISSUE THREAD

**Issue by authule** [credo-science/credo-webapp#43]
Dear colleagues,

it looks like it's impossible to download the data any longer (regardless of the data type, ping/detection); yet getting ping data was possible at least yesterday (18-Sep-2018) morning.

The download link generation is completed successfully, but after that there are some problems with connection, and when it's finally established, it's 
"HTTP request sent, awaiting response... 504 Gateway Time-out" message.

Could you please fix that?

**Comment by authule** [comment]
Thank you for your response,

Ping extraction looks to be fine, unlike detections - the output file is empty

**Comment by koziomek** [comment]
Please check your parameters. It seems like you were asking for detections between 1974-11-10T07:20:00+00:00 and 1974-11-13T18:40:00+00:00. I don't think there were many CREDO users in the '70s.

**Comment by koziomek** [comment]
Please also take a look at data-exporter and data-processor (https://github.com/credo-science/credo-api-tools).

These tools handle incremental export and processing of CREDO data.

**Comment by authule** [comment]
My bad, sorry
Thank you very much again

**Comment by koziomek** [comment]
Everything is now back to normal.
