### ISSUE TITLE
Delete user,  differences in the number of users in the team

### ISSUE THREAD

**Issue by slawekstu** [credo-science/credo-webapp#44]
Good morning,
I have two requests / questions:
1) I received a request from the team's mentor to delete the user:
Oko_słonia_w_dupie_węża
he is in the team: DELTA 3

2) Why are there different numbers of people in the team, on the ranking list and on the team's subpage?
For example: the IFJ team
Number of people on the ranking list: 51
Number of people on the team's subpage: 10

Such cases are for most bands, what does it result from?

**Comment by mpawlik** [comment]
Hello,

offensive username was changed.

Regarding team stats, I think that @koziomek will be able to help you with that matter.

**Comment by koziomek** [comment]
Regarding issue 2.
On team page we only show users with at least 1 visible detection.

**Comment by slawekstu** [comment]
A user wrote to me asking me to change the username.
At this moment, he gave his email as a username (timgj[at]hotmail.com). -> [at]=@
New username: "Noggin"
Is there a chance to change?
