### ISSUE TITLE
I need team name

### ISSUE THREAD

**Issue by slawekstu** [credo-science/credo-webapp#47]
I have a variable in data detections: "team_id"
but I can not get the name of the team.

I need this to display the results of specific teams (At this moment, there are 50 of them)
I know how to get a list of users and devices but How can I get team names?

Command:
python3 ./credo-data-exporter.py -u username -p password --mapping-type 'team'   -  not work
and
python3 ./credo-data-exporter.py -u username -p password --mapping-type 'team_id' - not work

**Comment by koziomek** [comment]
Support added in storage API: https://github.com/credo-science/credo-webapp/commit/ac119d6ae609f249b5c861581a7cf1b6208fd550
and in credo-exporter: https://github.com/credo-science/credo-api-tools/commit/022886b2ba0c99e78ee78126cdb5be1aae8eb13d
Mapping type is `team`.
