### ISSUE TITLE
How the detection filter works?

### ISSUE THREAD

**Issue by slawekstu** [credo-science/credo-webapp#48]
I wonder how filters work on the api.credo.science page. What data / values are the filters based on? Are these values included in packages that we can download?

The packages that can be downloaded are all detections without filters, so there are more than on the page.
Is an ordinary user able to reproduce this filter?
To be able to analyze only those detections that have been passed through the page filter?

**Comment by koziomek** [comment]
As of now, detection is hidden ("visible" attribute is set to false) if at least one of these conditions is true:
- it was submitted using old version of the API
- there is no image data associated with the detection
- average pixel brightness is above 15%
- original sensor coordinates of the brightest pixel for user submitting it are repeated ("hot pixels")
- timestamp of the detection is from before the user sent their first ping

These parameters and conditions were designed to provide better browsing experience for ordinary people wanting to look at pretty pictures.

> Are these values included in packages that we can download?

All of this information is present or can be created using data exports.

> Is an ordinary user able to reproduce this filter?

Does an average user know how to program? If so, yes. All of the code is open source and available to be reviewed.

> To be able to analyze only those detections that have been passed through the page filter?

I assume you want to know if scientists analyzing exported data are able to process only the detections that were classified as visible.

The answer is yes. However, in my opinion people analyzing this data should not depend on the visibility flag and instead using their understanding of the subject, create their own set of filters that would be probably more accurate.

**Comment by slawekstu** [comment]
Thank you for the answer, thanks to her I know how to take into account only those visible on the page (taking into account only those from: "visible" = "true")
