### ISSUE TITLE
credo-data-exporter.py

### ISSUE THREAD

**Issue by slawekstu** [credo-science/credo-webapp#50]
There is a problem with finding a link or file to download packages (credo-data-exporter.py).
New people who want to download data are not able to find this file quickly.
Especially if they do not know where to look
Could you add this file here? 
File or link where it will be found:
https://github.com/credo-science/credo-api-tools/tree/master/data-exporter

This should be on the same page on which the link carries api.credo.science namely:
https://github.com/credo-science/credo-webapp/tree/develop/credoapiv2#apiv2data_export

**Comment by koziomek** [comment]
Done in https://github.com/credo-science/credo-webapp/commit/5cc387cb77e7f4019340140cfa8083c937613876
