### ISSUE TITLE
Detection witout image data

### ISSUE THREAD

**Issue by mpawlik** [credo-science/credo-webapp#7]
Some detectors don't supply image with detection report. Model and services should accept such detections. This is a general ticket, if should be implemented in the model and apis.

**Comment by mpawlik** [comment]
Implemented in api v2, api v1 pending.

**Comment by mpawlik** [comment]
Done for api v1 in ceed03a678c4ddfc4dcdd930ff8566dc5dfb338b

It seems that handling of imageless detections in apiv2 was not tested. @koziomek could you make sure it works?:)

**Comment by koziomek** [comment]
Tested, it works.
